### ISSUE TITLE
BTC address service generateNewAddress() error

### ISSUE THREAD

**Issue by ismoli** [Crypto-APIs/Java-Library#3]
Getting following when calling `btc.getAddressService().generateNewAddress()`:

```
java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at io.cryptoapis.utils.rest.WebServices.httpsResponse(WebServices.java:117)
	at io.cryptoapis.utils.rest.WebServices.httpsRequest(WebServices.java:79)
	at io.cryptoapis.blockchains.bitcoin_based.services.AddressService.generateNewAddress(AddressService.java:42)
```
Debugging shows that endpoint is returning **http status 308** (works fine when calling from postman).

**Comment by ismoli** [comment]
Here is debugging screenshot to make it even clearer:

<img width="1096" alt="Screenshot 2019-11-18 at 18 36 56" src="https://user-images.githubusercontent.com/2808186/69075935-b20c1400-0a32-11ea-9ac5-1600b302f68c.png">

**Comment by jaysonmald35** [comment]
Thank u
